### ISSUE TITLE
Inquiry on QmxGraph documentation

### ISSUE THREAD

**Issue by lucaszhao19** [ESSS/qmxgraph#78]
Hello all. I am currently developing a Chemical Simulator diagramming application like draw.io using PyQt5. And found that there is a QmxGraph widget. I want to know that is there any documentation for this widget.

**Comment by prusse-martin** [comment]
No, sorry.
That is a really important and we have been missing it.

**Comment by lucaszhao19** [comment]
Thanks, looking forwards to it.

**Comment by nicoddemus** [comment]
Docs published now, courtesy of @prusse-martin: https://qmxgraph.readthedocs.io/en/latest/?badge=latest

Closing this for now, we have already further items to track in #37.
